---
stack_type: "docker"
stack_size: "4"
stack_type_provider: ""
stack_box_name: "ubuntu/xenial64"
stack_vm_memory: "2048"
stack_vm_cpus: "2"
tm_version: "v0.31.5"
mongo_version: "3.6"
azure_region: "westeurope"
azure_image_urn: "Canonical:UbuntuServer:16.04-LTS:latest"
azure_resource_group: "bdb-vagrant-rg-2024-02-12"
azure_dns_prefix: "bdb-instance-2024-02-12"
azure_admin_username: "vagrant"
azure_vm_size: "Standard_D2_v2"
ssh_private_key_path: ""
